spring:
  application:
    name: swagger-exercise-api-2
  web:
    resources:
      static-locations: classpath:/static/,file:${user.dir}/../openapi/

server:
  port: 8082

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
    config-url: /swagger-config.json

